---
  - name: install nginx web server
    become: true
    become_user: root
    become_method: su
    command: amazon-linux-extras install nginx1

  - name: setup server configuration
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/conf.d/nginx.conf
      owner: root

  - name: restart nginx
    service:
      name: nginx
      state: restarted