node {
	def app

	stage('Setup repository') {
		checkout scm
	}

	stage('Build image') {
		dir('./lesson-3') {
			app = docker.build("lesson-3-nginx:${env.BUILD_NUMBER} -f Dockerfile.nginx")
		}
	}

	stage('Push image') {
		docker.withRegistry('https://registry.hub.docker.com', 'docker-hub') {
			app.push("${env.BUILD_NUMBER}")
			app.push("latest")
		}
	}
}